name: dalel
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.2
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.10
  get_it: ^8.0.3
  persistent_bottom_nav_bar: ^6.2.1
  provider: ^6.1.2
  readmore: ^3.0.0
  shared_preferences: ^2.3.5
  shimmer: ^3.0.0
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/
  fonts:
    - family: Pacifico
      fonts:
        - asset: lib/assets/fonts/Pacifico-Regular.ttf
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
    - family: Saira
      fonts:
        - asset: lib/assets/fonts/Saira-Regular.ttf
flutter_assets:
  assets_path: lib/assets/images/
  output_path: lib/core/utils/
  filename: app_assets.dart
  field_prefix: null
flutter_intl:
  enabled: true
